const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');

const TEMPLATES = path.join(__dirname, '..', 'templates');

// ─── Helpers extracted from omni.js ──────────────────────────────────────────

function parseSource(raw) {
    if (!raw) return null;
    let cleaned = raw.trim().replace(/\/+$/, '');
    const urlMatch = cleaned.match(/^https?:\/\/(?:www\.)?github\.com\/([a-zA-Z0-9_-]+\/[a-zA-Z0-9._-]+(?:\/.+)?)$/);
    if (urlMatch) cleaned = urlMatch[1];
    const sshMatch = cleaned.match(/^git@github\.com:([a-zA-Z0-9_-]+\/[a-zA-Z0-9._-]+?)(?:\.git)?$/);
    if (sshMatch) cleaned = sshMatch[1];
    cleaned = cleaned.replace(/\.git$/, '');
    if (cleaned.includes('..')) return null;
    if (!/^[a-zA-Z0-9_-]+\/[a-zA-Z0-9._-]+(\/.+)?$/.test(cleaned)) return null;
    return cleaned;
}

function isValidSkillName(name) {
    return /^[a-z0-9-]+$/.test(name);
}

function buildRulesContent(rp) {
    const sections = [];
    if (rp.language) sections.push(`## Ngôn ngữ\n- ${rp.language}`);
    if (rp.codingStyle) sections.push(`## Coding Style\n${rp.codingStyle.split(';').map(r => r.trim()).filter(Boolean).map(r => `- ${r}`).join('\n')}`);
    if (rp.forbidden) sections.push(`## Forbidden Patterns\n${rp.forbidden.split(';').map(r => r.trim()).filter(Boolean).map(r => `- ${r}`).join('\n')}`);
    if (rp.custom) sections.push(`## Custom Rules\n${rp.custom.split(';').map(r => r.trim()).filter(Boolean).map(r => `- ${r}`).join('\n')}`);
    if (sections.length === 0) return null;
    return `# Personal Rules\n> Generated by Omni-Coder Kit | Last updated: ${new Date().toISOString().split('T')[0]}\n\n${sections.join('\n\n')}\n`;
}

function extractRulesForInject(rp) {
    const lines = [];
    if (rp.language) lines.push(`- **Ngôn ngữ:** ${rp.language}`);
    if (rp.codingStyle) rp.codingStyle.split(';').map(r => r.trim()).filter(Boolean).forEach(r => lines.push(`- ${r}`));
    if (rp.forbidden) rp.forbidden.split(';').map(r => r.trim()).filter(Boolean).forEach(r => lines.push(`- **KHÔNG:** ${r}`));
    if (rp.custom) rp.custom.split(';').map(r => r.trim()).filter(Boolean).forEach(r => lines.push(`- ${r}`));
    return lines.join('\n');
}

function createManifest() {
    return { version: '2.1.0', configFile: null, skills: { external: [] } };
}

const IDE_AGENT_MAP = {
    claudecode: ['claude-code'],
    codex: ['codex'],
    dual: ['claude-code', 'codex'],
    antigravity: ['antigravity'],
    cursor: ['cursor'],
    windsurf: ['windsurf'],
    agents: ['claude-code', 'codex', 'antigravity'],
    generic: null,
};

function getAgentFlags(manifest) {
    const agents = IDE_AGENT_MAP[manifest.ide];
    if (!agents) return '';
    return `--agent ${agents.join(' ')}`;
}

// ─── parseSource ─────────────────────────────────────────────────────────────

describe('parseSource', () => {
    it('parses owner/repo format', () => {
        assert.equal(parseSource('vercel-labs/skills'), 'vercel-labs/skills');
    });

    it('parses owner/repo with trailing slash', () => {
        assert.equal(parseSource('vercel-labs/skills/'), 'vercel-labs/skills');
    });

    it('parses full GitHub URL', () => {
        assert.equal(parseSource('https://github.com/obra/superpowers'), 'obra/superpowers');
    });

    it('parses GitHub URL with www', () => {
        assert.equal(parseSource('https://www.github.com/obra/superpowers'), 'obra/superpowers');
    });

    it('parses GitHub URL with subpath', () => {
        assert.equal(parseSource('https://github.com/owner/repo/tree/main/skills'), 'owner/repo/tree/main/skills');
    });

    it('parses git SSH format', () => {
        assert.equal(parseSource('git@github.com:owner/repo.git'), 'owner/repo');
    });

    it('strips .git suffix', () => {
        assert.equal(parseSource('owner/repo.git'), 'owner/repo');
    });

    it('returns null for empty input', () => {
        assert.equal(parseSource(''), null);
        assert.equal(parseSource(null), null);
        assert.equal(parseSource(undefined), null);
    });

    it('returns null for path traversal attempt', () => {
        assert.equal(parseSource('owner/../etc/passwd'), null);
    });

    it('returns null for single segment', () => {
        assert.equal(parseSource('just-a-name'), null);
    });

    it('handles whitespace', () => {
        assert.equal(parseSource('  vercel-labs/skills  '), 'vercel-labs/skills');
    });

    it('handles dots in repo name', () => {
        assert.equal(parseSource('owner/repo.name'), 'owner/repo.name');
    });

    it('handles underscores and hyphens', () => {
        assert.equal(parseSource('my_org/my-repo'), 'my_org/my-repo');
    });
});

// ─── isValidSkillName ────────────────────────────────────────────────────────

describe('isValidSkillName', () => {
    it('accepts lowercase with hyphens', () => {
        assert.ok(isValidSkillName('find-skills'));
        assert.ok(isValidSkillName('systematic-debugging'));
    });

    it('accepts lowercase alphanumeric', () => {
        assert.ok(isValidSkillName('skill123'));
    });

    it('rejects uppercase', () => {
        assert.ok(!isValidSkillName('FindSkills'));
    });

    it('rejects underscores', () => {
        assert.ok(!isValidSkillName('find_skills'));
    });

    it('rejects dots', () => {
        assert.ok(!isValidSkillName('my.skill'));
    });

    it('rejects spaces', () => {
        assert.ok(!isValidSkillName('my skill'));
    });

    it('rejects empty string', () => {
        assert.ok(!isValidSkillName(''));
    });
});

// ─── buildRulesContent ───────────────────────────────────────────────────────

describe('buildRulesContent', () => {
    it('returns null when all fields empty', () => {
        assert.equal(buildRulesContent({ language: '', codingStyle: '', forbidden: '', custom: '' }), null);
    });

    it('returns null when all fields undefined', () => {
        assert.equal(buildRulesContent({}), null);
    });

    it('builds language section', () => {
        const result = buildRulesContent({ language: 'Tiếng Việt' });
        assert.ok(result.includes('## Ngôn ngữ'));
        assert.ok(result.includes('- Tiếng Việt'));
        assert.ok(result.includes('# Personal Rules'));
    });

    it('builds coding style with semicolon splitting', () => {
        const result = buildRulesContent({ codingStyle: 'camelCase; 2-space indent; prefer const' });
        assert.ok(result.includes('## Coding Style'));
        assert.ok(result.includes('- camelCase'));
        assert.ok(result.includes('- 2-space indent'));
        assert.ok(result.includes('- prefer const'));
    });

    it('builds forbidden patterns', () => {
        const result = buildRulesContent({ forbidden: 'no any; no class components' });
        assert.ok(result.includes('## Forbidden Patterns'));
        assert.ok(result.includes('- no any'));
        assert.ok(result.includes('- no class components'));
    });

    it('builds custom rules', () => {
        const result = buildRulesContent({ custom: 'commit tiếng Việt; luôn viết test' });
        assert.ok(result.includes('## Custom Rules'));
        assert.ok(result.includes('- commit tiếng Việt'));
    });

    it('builds all sections together', () => {
        const result = buildRulesContent({
            language: 'English',
            codingStyle: 'PEP8',
            forbidden: 'no eval',
            custom: 'type hints required',
        });
        assert.ok(result.includes('## Ngôn ngữ'));
        assert.ok(result.includes('## Coding Style'));
        assert.ok(result.includes('## Forbidden Patterns'));
        assert.ok(result.includes('## Custom Rules'));
    });

    it('includes date in header', () => {
        const result = buildRulesContent({ language: 'English' });
        const today = new Date().toISOString().split('T')[0];
        assert.ok(result.includes(today));
    });

    it('filters empty segments from semicolons', () => {
        const result = buildRulesContent({ codingStyle: 'rule1;; ;rule2' });
        assert.ok(result.includes('- rule1'));
        assert.ok(result.includes('- rule2'));
        assert.ok(!result.includes('- \n'));
    });
});

// ─── extractRulesForInject ───────────────────────────────────────────────────

describe('extractRulesForInject', () => {
    it('formats language with bold label', () => {
        const result = extractRulesForInject({ language: 'Tiếng Việt' });
        assert.ok(result.includes('**Ngôn ngữ:**'));
        assert.ok(result.includes('Tiếng Việt'));
    });

    it('formats forbidden with KHÔNG prefix', () => {
        const result = extractRulesForInject({ forbidden: 'no any; no eval' });
        assert.ok(result.includes('**KHÔNG:** no any'));
        assert.ok(result.includes('**KHÔNG:** no eval'));
    });

    it('returns empty string when no rules', () => {
        assert.equal(extractRulesForInject({}), '');
    });

    it('combines all rule types', () => {
        const result = extractRulesForInject({
            language: 'English',
            codingStyle: 'camelCase',
            forbidden: 'no var',
            custom: 'use pnpm',
        });
        const lines = result.split('\n');
        assert.equal(lines.length, 4);
    });
});

// ─── createManifest ──────────────────────────────────────────────────────────

describe('createManifest', () => {
    it('returns correct default structure', () => {
        const m = createManifest();
        assert.equal(m.version, '2.1.0');
        assert.equal(m.configFile, null);
        assert.ok(Array.isArray(m.skills.external));
        assert.equal(m.skills.external.length, 0);
    });

    it('returns a new object each call', () => {
        const a = createManifest();
        const b = createManifest();
        assert.notEqual(a, b);
        a.configFile = 'test';
        assert.equal(b.configFile, null);
    });
});

// ─── getAgentFlags ───────────────────────────────────────────────────────────

describe('getAgentFlags', () => {
    it('returns correct flags for claudecode', () => {
        assert.equal(getAgentFlags({ ide: 'claudecode' }), '--agent claude-code');
    });

    it('returns correct flags for codex', () => {
        assert.equal(getAgentFlags({ ide: 'codex' }), '--agent codex');
    });

    it('returns correct flags for dual', () => {
        assert.equal(getAgentFlags({ ide: 'dual' }), '--agent claude-code codex');
    });

    it('returns correct flags for agents', () => {
        assert.equal(getAgentFlags({ ide: 'agents' }), '--agent claude-code codex antigravity');
    });

    it('returns empty string for generic', () => {
        assert.equal(getAgentFlags({ ide: 'generic' }), '');
    });
});

// ─── getOverlayNameForTarget — cursor ────────────────────────────────────────

function getOverlayNameForTarget(ide, target) {
    if (target === 'claude-code') {
        return (ide === 'claudecode' || ide === 'dual') ? 'claude-code' : null;
    }
    if (target === 'codex') {
        return (ide === 'codex' || ide === 'dual') ? 'codex' : null;
    }
    if (target === 'cursor') {
        return (ide === 'cursor') ? 'cursor' : null;
    }
    return null;
}

describe('getOverlayNameForTarget — cursor', () => {
    it('returns "cursor" for ide=cursor, target=cursor', () => {
        assert.equal(getOverlayNameForTarget('cursor', 'cursor'), 'cursor');
    });

    it('returns null for ide=claudecode, target=cursor', () => {
        assert.equal(getOverlayNameForTarget('claudecode', 'cursor'), null);
    });

    it('returns null for ide=cursor, target=claude-code', () => {
        assert.equal(getOverlayNameForTarget('cursor', 'claude-code'), null);
    });

    it('returns null for ide=codex, target=cursor', () => {
        assert.equal(getOverlayNameForTarget('codex', 'cursor'), null);
    });
});

// ─── Core template files exist ───────────────────────────────────────────────

describe('Core template files exist', () => {
    const coreFiles = [
        'core/karpathy-mindset.md',
        'core/claudex-hygiene.md',
    ];

    for (const file of coreFiles) {
        it(`${file} exists and is non-empty`, () => {
            const p = path.join(TEMPLATES, file);
            assert.ok(fs.existsSync(p), `${file} should exist`);
            const content = fs.readFileSync(p, 'utf-8');
            assert.ok(content.length > 100, `${file} should have substantial content`);
        });
    }
});

// ─── Base workflow files exist ───────────────────────────────────────────────

describe('Base workflow files exist', () => {
    const expectedWorkflows = [
        'coder-execution.md',
        'debugger-workflow.md',
        'documentation-writer.md',
        'interview-examples.md',
        'knowledge-learn.md',
        'pm-templates.md',
        'qa-testing.md',
        'requirement-analysis.md',
        'skill-manager.md',
        'superpower-sdlc.md',
        'task-planning.md',
        'validation-scripts.md',
    ];

    for (const wf of expectedWorkflows) {
        it(`workflows/${wf} exists`, () => {
            assert.ok(fs.existsSync(path.join(TEMPLATES, 'workflows', wf)));
        });
    }
});

// ─── detectDNA ──────────────────────────────────────────────────────────────

function detectDNA(projectDir) {
    let pkg = {};
    try {
        pkg = JSON.parse(fs.readFileSync(path.join(projectDir, 'package.json'), 'utf-8'));
    } catch {}

    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    const hasDep = (name) => name in allDeps;
    const dirExists = (name) => fs.existsSync(path.join(projectDir, name));

    return {
        hasUI: hasDep('react') || hasDep('vue') || hasDep('svelte') || hasDep('next') || hasDep('@angular/core'),
        hasBackend: hasDep('express') || hasDep('fastify') || hasDep('hono') || hasDep('prisma') || hasDep('@supabase/supabase-js') || dirExists('server') || dirExists('api'),
        hasAPI: hasDep('express') || hasDep('fastify') || hasDep('hono') || dirExists('routes') || dirExists('controllers'),
    };
}

describe('detectDNA', () => {
    it('returns all false for empty project', () => {
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omni-dna-test-'));
        try {
            const dna = detectDNA(tmpDir);
            assert.equal(dna.hasUI, false);
            assert.equal(dna.hasBackend, false);
            assert.equal(dna.hasAPI, false);
        } finally {
            fs.rmSync(tmpDir, { recursive: true, force: true });
        }
    });

    it('detects hasUI from React dependency', () => {
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omni-dna-test-'));
        try {
            fs.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify({
                dependencies: { react: '^18.0.0', 'react-dom': '^18.0.0' }
            }));
            const dna = detectDNA(tmpDir);
            assert.equal(dna.hasUI, true);
            assert.equal(dna.hasBackend, false);
        } finally {
            fs.rmSync(tmpDir, { recursive: true, force: true });
        }
    });

    it('detects hasBackend from Express dependency', () => {
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omni-dna-test-'));
        try {
            fs.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify({
                dependencies: { express: '^4.18.0' }
            }));
            const dna = detectDNA(tmpDir);
            assert.equal(dna.hasBackend, true);
            assert.equal(dna.hasAPI, true);
            assert.equal(dna.hasUI, false);
        } finally {
            fs.rmSync(tmpDir, { recursive: true, force: true });
        }
    });

    it('detects hasBackend from server directory', () => {
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omni-dna-test-'));
        try {
            fs.mkdirSync(path.join(tmpDir, 'server'));
            const dna = detectDNA(tmpDir);
            assert.equal(dna.hasBackend, true);
        } finally {
            fs.rmSync(tmpDir, { recursive: true, force: true });
        }
    });

    it('detects hasAPI from routes directory', () => {
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omni-dna-test-'));
        try {
            fs.mkdirSync(path.join(tmpDir, 'routes'));
            const dna = detectDNA(tmpDir);
            assert.equal(dna.hasAPI, true);
        } finally {
            fs.rmSync(tmpDir, { recursive: true, force: true });
        }
    });

    it('detects fullstack project (React + Express)', () => {
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omni-dna-test-'));
        try {
            fs.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify({
                dependencies: { react: '^18.0.0', express: '^4.18.0' }
            }));
            const dna = detectDNA(tmpDir);
            assert.equal(dna.hasUI, true);
            assert.equal(dna.hasBackend, true);
            assert.equal(dna.hasAPI, true);
        } finally {
            fs.rmSync(tmpDir, { recursive: true, force: true });
        }
    });
});
