const { describe, it, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');

const TEMPLATES = path.join(__dirname, '..', 'templates');

// ─── Helpers extracted from omni.js ──────────────────────────────────────────

function getOverlayNameForTarget(ide, target) {
    if (target === 'claude-code') {
        return (ide === 'claudecode' || ide === 'dual') ? 'claude-code' : null;
    }
    if (target === 'codex') {
        return (ide === 'codex' || ide === 'dual') ? 'codex' : null;
    }
    return null;
}

function getOverlayDir(ide, target = null) {
    const overlayName = target
        ? getOverlayNameForTarget(ide, target)
        : ({ claudecode: 'claude-code', dual: 'claude-code' }[ide] || null);
    if (!overlayName) return null;
    const dir = path.join(TEMPLATES, 'overlays', overlayName);
    return fs.existsSync(dir) ? dir : null;
}

function buildWorkflows(ide, target = null) {
    const baseDir = path.join(TEMPLATES, 'workflows');
    const files = {};
    for (const f of fs.readdirSync(baseDir).filter(f => f.endsWith('.md'))) {
        files[f] = path.join(baseDir, f);
    }
    const overlayDir = getOverlayDir(ide, target);
    if (overlayDir) {
        const overlayWorkflowDir = path.join(overlayDir, 'workflows');
        if (fs.existsSync(overlayWorkflowDir)) {
            for (const f of fs.readdirSync(overlayWorkflowDir).filter(f => f.endsWith('.md'))) {
                files[f] = path.join(overlayWorkflowDir, f);
            }
        }
    }
    return files;
}

function buildCommands(ide) {
    if (!(ide === 'claudecode' || ide === 'dual')) return null;
    const overlayDir = getOverlayDir(ide, 'claude-code');
    if (!overlayDir) return null;
    const commandsDir = path.join(overlayDir, 'commands');
    if (!fs.existsSync(commandsDir)) return null;
    const files = {};
    for (const f of fs.readdirSync(commandsDir).filter(f => f.endsWith('.md'))) {
        files[f] = path.join(commandsDir, f);
    }
    return Object.keys(files).length > 0 ? files : null;
}

function buildSettings(ide, advanced) {
    if (!advanced) return null;
    const overlayDir = getOverlayDir(ide);
    if (!overlayDir) return null;
    const templatePath = path.join(overlayDir, 'settings.template.json');
    if (!fs.existsSync(templatePath)) return null;
    return fs.readFileSync(templatePath, 'utf-8');
}

function buildCodexConfig(ide, advanced) {
    if (!advanced || !(ide === 'codex' || ide === 'dual')) return null;
    const overlayDir = getOverlayDir(ide, 'codex');
    if (!overlayDir) return null;
    const templatePath = path.join(overlayDir, 'config.template.toml');
    if (!fs.existsSync(templatePath)) return null;
    return fs.readFileSync(templatePath, 'utf-8');
}

function buildCodexHooks(ide, advanced) {
    if (!advanced || !(ide === 'codex' || ide === 'dual')) return null;
    const overlayDir = getOverlayDir(ide, 'codex');
    if (!overlayDir) return null;
    const templatePath = path.join(overlayDir, 'hooks.template.json');
    if (!fs.existsSync(templatePath)) return null;
    return fs.readFileSync(templatePath, 'utf-8');
}

function readTemplate(filePath) {
    return fs.readFileSync(filePath, 'utf-8');
}

// ─── Expected config file per IDE ────────────────────────────────────────────

const IDE_CONFIG_MAP = {
    claudecode: 'CLAUDE.md',
    codex: 'AGENTS.md',
    dual: 'CLAUDE.md',
    antigravity: 'AGENTS.md',
    cursor: '.cursorrules',
    windsurf: '.windsurfrules',
    agents: 'AGENTS.md',
    generic: 'SYSTEM_PROMPT.md',
};

// ─── Temp dir helper ─────────────────────────────────────────────────────────

function makeTmpDir() {
    return fs.mkdtempSync(path.join(os.tmpdir(), 'omni-init-test-'));
}

// ─── Simulate init for any IDE ───────────────────────────────────────────────

function simulateInit(ide, opts = {}) {
    const tmpDir = makeTmpDir();
    const result = { tmpDir, files: {} };

    const mindset = readTemplate(path.join(TEMPLATES, 'core', 'karpathy-mindset.md'));
    const hygiene = readTemplate(path.join(TEMPLATES, 'core', 'claudex-hygiene.md'));

    // Workflows
    const workflowsDir = path.join(tmpDir, '.omni', 'workflows');
    fs.mkdirSync(workflowsDir, { recursive: true });

    const workflowTarget = ide === 'codex' ? 'codex' : ide === 'dual' ? 'base' : null;
    const mergedWorkflows = buildWorkflows(ide, workflowTarget);
    for (const [name, srcPath] of Object.entries(mergedWorkflows)) {
        fs.copyFileSync(srcPath, path.join(workflowsDir, name));
    }
    result.files.workflows = Object.keys(mergedWorkflows);

    // Config file
    const fileName = IDE_CONFIG_MAP[ide];
    let content = `> Generated by Omni-Coder Kit\n\n${mindset}\n\n${hygiene}\n\n`;
    content += `## IDE SPECIFIC ADAPTERS\n`;

    fs.writeFileSync(path.join(tmpDir, fileName), content);
    result.files.configFile = fileName;

    // Slash commands (Claude Code only)
    const slashCommands = buildCommands(ide);
    if (slashCommands) {
        const claudeCommandsDir = path.join(tmpDir, '.claude', 'commands');
        fs.mkdirSync(claudeCommandsDir, { recursive: true });
        for (const [name, srcPath] of Object.entries(slashCommands)) {
            fs.copyFileSync(srcPath, path.join(claudeCommandsDir, name));
        }
        result.files.commands = Object.keys(slashCommands);
    }

    // Claude settings (advanced)
    if (opts.advanced) {
        const settings = buildSettings(ide, true);
        if (settings) {
            const claudeDir = path.join(tmpDir, '.claude');
            fs.mkdirSync(claudeDir, { recursive: true });
            fs.writeFileSync(path.join(claudeDir, 'settings.json'), settings);
            result.files.settings = true;
        }

        const codexConfig = buildCodexConfig(ide, true);
        const codexHooks = buildCodexHooks(ide, true);
        if (codexConfig || codexHooks) {
            const codexDir = path.join(tmpDir, '.codex');
            fs.mkdirSync(codexDir, { recursive: true });
            if (codexConfig) fs.writeFileSync(path.join(codexDir, 'config.toml'), codexConfig);
            if (codexHooks) fs.writeFileSync(path.join(codexDir, 'hooks.json'), codexHooks);
            result.files.codexConfig = !!codexConfig;
            result.files.codexHooks = !!codexHooks;
        }
    }

    // Dual mode: AGENTS.md
    if (ide === 'dual') {
        const agentsContent = `> Generated by Omni-Coder Kit (Codex CLI / Cross-tool)\n\n${mindset}\n\n${hygiene}\n`;
        fs.writeFileSync(path.join(tmpDir, 'AGENTS.md'), agentsContent);
        result.files.agentsMd = true;
    }

    // Manifest
    const manifest = {
        version: '2.1.0',
        configFile: fileName,
        ide,
        skills: { external: [] },
    };
    fs.writeFileSync(path.join(tmpDir, '.omni-manifest.json'), JSON.stringify(manifest, null, 2));
    result.manifest = manifest;

    return result;
}

// ─── Claude Code init ────────────────────────────────────────────────────────

describe('E2E: claudecode init', () => {
    let result;

    beforeEach(() => { result = simulateInit('claudecode', { advanced: true }); });
    afterEach(() => { fs.rmSync(result.tmpDir, { recursive: true, force: true }); });

    it('creates CLAUDE.md', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, 'CLAUDE.md')));
    });

    it('CLAUDE.md includes mindset and hygiene', () => {
        const content = fs.readFileSync(path.join(result.tmpDir, 'CLAUDE.md'), 'utf-8');
        assert.ok(content.includes('CORE MINDSET'));
        assert.ok(content.includes('CONTEXT HYGIENE'));
    });

    it('creates all base workflows in .omni/workflows/', () => {
        const baseWorkflows = fs.readdirSync(path.join(TEMPLATES, 'workflows')).filter(f => f.endsWith('.md'));
        const outputWorkflows = fs.readdirSync(path.join(result.tmpDir, '.omni', 'workflows'));
        for (const wf of baseWorkflows) {
            assert.ok(outputWorkflows.includes(wf), `${wf} should exist`);
        }
    });

    it('applies claude-code workflow overlay (coder-execution.md)', () => {
        const content = fs.readFileSync(path.join(result.tmpDir, '.omni', 'workflows', 'coder-execution.md'), 'utf-8');
        const overlayContent = fs.readFileSync(
            path.join(TEMPLATES, 'overlays', 'claude-code', 'workflows', 'coder-execution.md'), 'utf-8'
        );
        assert.equal(content, overlayContent);
    });

    it('creates 7 slash commands in .claude/commands/', () => {
        const cmdsDir = path.join(result.tmpDir, '.claude', 'commands');
        assert.ok(fs.existsSync(cmdsDir));
        const cmds = fs.readdirSync(cmdsDir).filter(f => f.endsWith('.md'));
        assert.equal(cmds.length, 7);
        assert.ok(cmds.includes('om:brainstorm.md'));
        assert.ok(cmds.includes('om:cook.md'));
        assert.ok(cmds.includes('om:plan.md'));
        assert.ok(cmds.includes('om:check.md'));
        assert.ok(cmds.includes('om:fix.md'));
        assert.ok(cmds.includes('om:doc.md'));
        assert.ok(cmds.includes('om:equip.md'));
    });

    it('creates .claude/settings.json with advanced setup', () => {
        const settingsPath = path.join(result.tmpDir, '.claude', 'settings.json');
        assert.ok(fs.existsSync(settingsPath));
        const settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
        assert.ok(settings.permissions);
        assert.ok(settings.permissions.allow.length > 0);
        assert.ok(settings.permissions.deny.length > 0);
        assert.ok(settings.hooks);
    });

    it('settings.json deny list includes dangerous commands', () => {
        const settings = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.claude', 'settings.json'), 'utf-8')
        );
        const deny = settings.permissions.deny;
        assert.ok(deny.some(d => d.includes('rm -rf')));
        assert.ok(deny.some(d => d.includes('push --force')));
        assert.ok(deny.some(d => d.includes('reset --hard')));
    });

    it('creates manifest with correct IDE', () => {
        const manifest = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.omni-manifest.json'), 'utf-8')
        );
        assert.equal(manifest.ide, 'claudecode');
        assert.equal(manifest.configFile, 'CLAUDE.md');
    });

    it('does NOT create codex files', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.codex')));
        assert.ok(!fs.existsSync(path.join(result.tmpDir, 'AGENTS.md')));
    });
});

// ─── Claude Code overlay content integrity ───────────────────────────────────

describe('Claude Code overlay content integrity', () => {
    it('coder-execution.md references subagent delegation', () => {
        const content = fs.readFileSync(
            path.join(TEMPLATES, 'overlays', 'claude-code', 'workflows', 'coder-execution.md'), 'utf-8'
        );
        assert.ok(content.includes('sub-agent') || content.includes('subagent') || content.includes('Sub-Agent'));
    });

    it('superpower-sdlc.md references Claude Code slash commands', () => {
        const content = fs.readFileSync(
            path.join(TEMPLATES, 'overlays', 'claude-code', 'workflows', 'superpower-sdlc.md'), 'utf-8'
        );
        assert.ok(content.includes('/om:') || content.includes('>om:'));
    });

    it('all 7 slash command files reference workflow paths', () => {
        const cmdsDir = path.join(TEMPLATES, 'overlays', 'claude-code', 'commands');
        const cmds = fs.readdirSync(cmdsDir).filter(f => f.endsWith('.md'));
        for (const cmd of cmds) {
            const content = fs.readFileSync(path.join(cmdsDir, cmd), 'utf-8');
            assert.ok(
                content.includes('.omni/workflows/') || content.includes('omni/workflows'),
                `${cmd} should reference workflow file`
            );
        }
    });

    it('settings.template.json is valid JSON', () => {
        const content = fs.readFileSync(
            path.join(TEMPLATES, 'overlays', 'claude-code', 'settings.template.json'), 'utf-8'
        );
        assert.doesNotThrow(() => JSON.parse(content));
    });
});

// ─── Dual init ───────────────────────────────────────────────────────────────

describe('E2E: dual init', () => {
    let result;

    beforeEach(() => { result = simulateInit('dual', { advanced: true }); });
    afterEach(() => { fs.rmSync(result.tmpDir, { recursive: true, force: true }); });

    it('creates both CLAUDE.md and AGENTS.md', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, 'CLAUDE.md')));
        assert.ok(fs.existsSync(path.join(result.tmpDir, 'AGENTS.md')));
    });

    it('creates Claude slash commands', () => {
        const cmdsDir = path.join(result.tmpDir, '.claude', 'commands');
        assert.ok(fs.existsSync(cmdsDir));
        assert.equal(fs.readdirSync(cmdsDir).filter(f => f.endsWith('.md')).length, 7);
    });

    it('creates Claude settings', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, '.claude', 'settings.json')));
    });

    it('creates Codex config and hooks', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, '.codex', 'config.toml')));
        assert.ok(fs.existsSync(path.join(result.tmpDir, '.codex', 'hooks.json')));
    });

    it('workflows use base (no overlay) for dual mode', () => {
        const content = fs.readFileSync(
            path.join(result.tmpDir, '.omni', 'workflows', 'coder-execution.md'), 'utf-8'
        );
        const baseContent = fs.readFileSync(
            path.join(TEMPLATES, 'workflows', 'coder-execution.md'), 'utf-8'
        );
        assert.equal(content, baseContent);
    });

    it('manifest records dual IDE', () => {
        const manifest = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.omni-manifest.json'), 'utf-8')
        );
        assert.equal(manifest.ide, 'dual');
    });
});

// ─── Antigravity init ────────────────────────────────────────────────────────

describe('E2E: antigravity init', () => {
    let result;

    beforeEach(() => { result = simulateInit('antigravity'); });
    afterEach(() => { fs.rmSync(result.tmpDir, { recursive: true, force: true }); });

    it('creates AGENTS.md', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, 'AGENTS.md')));
    });

    it('does NOT create CLAUDE.md', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, 'CLAUDE.md')));
    });

    it('does NOT create .claude/ directory', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.claude')));
    });

    it('does NOT create .codex/ directory', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.codex')));
    });

    it('creates all workflows', () => {
        const baseWorkflows = fs.readdirSync(path.join(TEMPLATES, 'workflows')).filter(f => f.endsWith('.md'));
        const outputWorkflows = fs.readdirSync(path.join(result.tmpDir, '.omni', 'workflows'));
        for (const wf of baseWorkflows) {
            assert.ok(outputWorkflows.includes(wf));
        }
    });

    it('uses base workflows (no overlay)', () => {
        const content = fs.readFileSync(
            path.join(result.tmpDir, '.omni', 'workflows', 'coder-execution.md'), 'utf-8'
        );
        const baseContent = fs.readFileSync(
            path.join(TEMPLATES, 'workflows', 'coder-execution.md'), 'utf-8'
        );
        assert.equal(content, baseContent);
    });

    it('manifest records antigravity IDE', () => {
        const manifest = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.omni-manifest.json'), 'utf-8')
        );
        assert.equal(manifest.ide, 'antigravity');
        assert.equal(manifest.configFile, 'AGENTS.md');
    });
});

// ─── Cursor init ─────────────────────────────────────────────────────────────

describe('E2E: cursor init', () => {
    let result;

    beforeEach(() => { result = simulateInit('cursor'); });
    afterEach(() => { fs.rmSync(result.tmpDir, { recursive: true, force: true }); });

    it('creates .cursorrules', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, '.cursorrules')));
    });

    it('.cursorrules includes mindset', () => {
        const content = fs.readFileSync(path.join(result.tmpDir, '.cursorrules'), 'utf-8');
        assert.ok(content.includes('CORE MINDSET'));
    });

    it('does NOT create .claude/ or .codex/', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.claude')));
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.codex')));
    });

    it('does NOT create slash commands', () => {
        assert.equal(result.files.commands, undefined);
    });

    it('manifest records cursor IDE', () => {
        const manifest = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.omni-manifest.json'), 'utf-8')
        );
        assert.equal(manifest.ide, 'cursor');
        assert.equal(manifest.configFile, '.cursorrules');
    });
});

// ─── Windsurf init ───────────────────────────────────────────────────────────

describe('E2E: windsurf init', () => {
    let result;

    beforeEach(() => { result = simulateInit('windsurf'); });
    afterEach(() => { fs.rmSync(result.tmpDir, { recursive: true, force: true }); });

    it('creates .windsurfrules', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, '.windsurfrules')));
    });

    it('.windsurfrules includes hygiene', () => {
        const content = fs.readFileSync(path.join(result.tmpDir, '.windsurfrules'), 'utf-8');
        assert.ok(content.includes('CONTEXT HYGIENE'));
    });

    it('does NOT create .claude/ or .codex/', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.claude')));
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.codex')));
    });

    it('manifest records windsurf IDE', () => {
        const manifest = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.omni-manifest.json'), 'utf-8')
        );
        assert.equal(manifest.ide, 'windsurf');
        assert.equal(manifest.configFile, '.windsurfrules');
    });
});

// ─── Cross-tool (agents) init ────────────────────────────────────────────────

describe('E2E: agents init', () => {
    let result;

    beforeEach(() => { result = simulateInit('agents'); });
    afterEach(() => { fs.rmSync(result.tmpDir, { recursive: true, force: true }); });

    it('creates AGENTS.md', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, 'AGENTS.md')));
    });

    it('does NOT create CLAUDE.md', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, 'CLAUDE.md')));
    });

    it('manifest records agents IDE', () => {
        const manifest = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.omni-manifest.json'), 'utf-8')
        );
        assert.equal(manifest.ide, 'agents');
        assert.equal(manifest.configFile, 'AGENTS.md');
    });
});

// ─── Generic init ────────────────────────────────────────────────────────────

describe('E2E: generic init', () => {
    let result;

    beforeEach(() => { result = simulateInit('generic'); });
    afterEach(() => { fs.rmSync(result.tmpDir, { recursive: true, force: true }); });

    it('creates SYSTEM_PROMPT.md', () => {
        assert.ok(fs.existsSync(path.join(result.tmpDir, 'SYSTEM_PROMPT.md')));
    });

    it('does NOT create any tool-specific dirs', () => {
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.claude')));
        assert.ok(!fs.existsSync(path.join(result.tmpDir, '.codex')));
        assert.ok(!fs.existsSync(path.join(result.tmpDir, 'CLAUDE.md')));
        assert.ok(!fs.existsSync(path.join(result.tmpDir, 'AGENTS.md')));
    });

    it('manifest records generic IDE', () => {
        const manifest = JSON.parse(
            fs.readFileSync(path.join(result.tmpDir, '.omni-manifest.json'), 'utf-8')
        );
        assert.equal(manifest.ide, 'generic');
        assert.equal(manifest.configFile, 'SYSTEM_PROMPT.md');
    });
});

// ─── Cross-IDE: no overlay contamination ─────────────────────────────────────

describe('Cross-IDE isolation', () => {
    const nonOverlayIDEs = ['antigravity', 'cursor', 'windsurf', 'agents', 'generic'];

    for (const ide of nonOverlayIDEs) {
        it(`${ide}: workflows are all base (no overlay)`, () => {
            const result = simulateInit(ide);
            try {
                const baseWorkflows = fs.readdirSync(path.join(TEMPLATES, 'workflows')).filter(f => f.endsWith('.md'));
                for (const wf of baseWorkflows) {
                    const outputContent = fs.readFileSync(
                        path.join(result.tmpDir, '.omni', 'workflows', wf), 'utf-8'
                    );
                    const baseContent = fs.readFileSync(
                        path.join(TEMPLATES, 'workflows', wf), 'utf-8'
                    );
                    assert.equal(outputContent, baseContent, `${ide}:${wf} should match base`);
                }
            } finally {
                fs.rmSync(result.tmpDir, { recursive: true, force: true });
            }
        });
    }
});

// ─── Overlay system: buildSettings edge cases ────────────────────────────────

describe('buildSettings', () => {
    it('returns settings for claudecode + advanced', () => {
        const s = buildSettings('claudecode', true);
        assert.ok(s);
        const parsed = JSON.parse(s);
        assert.ok(parsed.permissions);
    });

    it('returns settings for dual + advanced', () => {
        assert.ok(buildSettings('dual', true));
    });

    it('returns null when advanced is false', () => {
        assert.equal(buildSettings('claudecode', false), null);
    });

    it('returns null for codex (no claude settings)', () => {
        assert.equal(buildSettings('codex', true), null);
    });

    it('returns null for cursor', () => {
        assert.equal(buildSettings('cursor', true), null);
    });

    it('returns null for generic', () => {
        assert.equal(buildSettings('generic', true), null);
    });
});

// ─── Overlay template file completeness ──────────────────────────────────────

describe('Claude Code overlay template files exist', () => {
    const requiredFiles = [
        'overlays/claude-code/settings.template.json',
        'overlays/claude-code/commands/om:brainstorm.md',
        'overlays/claude-code/commands/om:cook.md',
        'overlays/claude-code/commands/om:plan.md',
        'overlays/claude-code/commands/om:check.md',
        'overlays/claude-code/commands/om:fix.md',
        'overlays/claude-code/commands/om:doc.md',
        'overlays/claude-code/commands/om:equip.md',
        'overlays/claude-code/workflows/coder-execution.md',
        'overlays/claude-code/workflows/superpower-sdlc.md',
    ];

    for (const file of requiredFiles) {
        it(`${file} exists`, () => {
            assert.ok(fs.existsSync(path.join(TEMPLATES, file)));
        });
    }
});
