'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');

const { buildInitConfig, buildModeBlock } = require('../lib/init');

const DEFAULT_OPTS = {
    mode: 'manual',
    parsedRules: null,
    rulesContent: null,
    projectDir: process.cwd(),
    dnaProfile: { hasUI: false, hasBackend: false, hasAPI: false },
    subagents: false,
};

// ─── Structure tests ────────────────────────────────────────────

describe('buildInitConfig return shape', () => {
    it('returns files, dirs, and manifest', () => {
        const result = buildInitConfig('claudecode', DEFAULT_OPTS);
        assert.ok(Array.isArray(result.files), 'files should be an array');
        assert.ok(Array.isArray(result.dirs), 'dirs should be an array');
        assert.ok(result.manifest && typeof result.manifest === 'object', 'manifest should be an object');
    });

    it('dirs includes .omni/workflows', () => {
        const result = buildInitConfig('claudecode', DEFAULT_OPTS);
        assert.ok(result.dirs.some(d => d.includes(path.join('.omni', 'workflows'))));
    });
});

// ─── Per-IDE config file tests ──────────────────────────────────

describe('buildInitConfig per-IDE config files', () => {
    it('claudecode produces CLAUDE.md', () => {
        const result = buildInitConfig('claudecode', DEFAULT_OPTS);
        const main = result.files.find(f => f.overwritePrompt && f.path === 'CLAUDE.md');
        assert.ok(main, 'should have CLAUDE.md');
        assert.ok(main.content.includes('Generated by Omni-Coder Kit'));
    });

    it('codex produces AGENTS.md', () => {
        const result = buildInitConfig('codex', DEFAULT_OPTS);
        const main = result.files.find(f => f.overwritePrompt && f.path === 'AGENTS.md');
        assert.ok(main, 'should have AGENTS.md');
    });

    it('dual produces both CLAUDE.md and AGENTS.md', () => {
        const result = buildInitConfig('dual', DEFAULT_OPTS);
        const claude = result.files.find(f => f.path === 'CLAUDE.md');
        const agents = result.files.find(f => f.path === 'AGENTS.md');
        assert.ok(claude, 'should have CLAUDE.md');
        assert.ok(agents, 'should have AGENTS.md');
        assert.ok(agents.content.includes('Codex CLI / Cross-tool'));
    });

    it('cursor produces .cursorrules', () => {
        const result = buildInitConfig('cursor', DEFAULT_OPTS);
        const main = result.files.find(f => f.overwritePrompt && f.path === '.cursorrules');
        assert.ok(main, 'should have .cursorrules');
    });

    it('gemini produces GEMINI.md', () => {
        const result = buildInitConfig('gemini', DEFAULT_OPTS);
        const main = result.files.find(f => f.overwritePrompt && f.path === 'GEMINI.md');
        assert.ok(main, 'should have GEMINI.md');
    });

    it('windsurf produces .windsurfrules', () => {
        const result = buildInitConfig('windsurf', DEFAULT_OPTS);
        const main = result.files.find(f => f.overwritePrompt && f.path === '.windsurfrules');
        assert.ok(main, 'should have .windsurfrules');
    });

    it('generic produces SYSTEM_PROMPT.md', () => {
        const result = buildInitConfig('generic', DEFAULT_OPTS);
        const main = result.files.find(f => f.overwritePrompt && f.path === 'SYSTEM_PROMPT.md');
        assert.ok(main, 'should have SYSTEM_PROMPT.md');
    });
});

// ─── Personal rules ─────────────────────────────────────────────

describe('buildInitConfig personal rules', () => {
    it('includes .omni/rules.md when rulesContent is provided', () => {
        const opts = { ...DEFAULT_OPTS, rulesContent: '# My Rules', parsedRules: { language: 'en', codingStyle: [], forbidden: [], custom: [] } };
        const result = buildInitConfig('claudecode', opts);
        const rulesFile = result.files.find(f => f.path === path.join('.omni', 'rules.md'));
        assert.ok(rulesFile, 'should include rules.md');
        assert.equal(rulesFile.content, '# My Rules');
        assert.equal(rulesFile.overwritePrompt, false);
    });

    it('does NOT include rules.md when rulesContent is null', () => {
        const result = buildInitConfig('claudecode', DEFAULT_OPTS);
        const rulesFile = result.files.find(f => f.path === path.join('.omni', 'rules.md'));
        assert.equal(rulesFile, undefined, 'should not include rules.md');
    });
});

// ─── Manifest ───────────────────────────────────────────────────

describe('buildInitConfig manifest', () => {
    it('manifest has correct ide and configFile', () => {
        const result = buildInitConfig('claudecode', DEFAULT_OPTS);
        assert.equal(result.manifest.ide, 'claudecode');
        assert.equal(result.manifest.configFile, 'CLAUDE.md');
    });

    it('manifest has correct configFile for codex', () => {
        const result = buildInitConfig('codex', DEFAULT_OPTS);
        assert.equal(result.manifest.configFile, 'AGENTS.md');
    });

    it('manifest includes subagents for supported IDEs', () => {
        const result = buildInitConfig('claudecode', { ...DEFAULT_OPTS, subagents: true });
        assert.equal(result.manifest.subagents, true);
    });

    it('manifest does not include subagents for unsupported IDEs', () => {
        const result = buildInitConfig('cursor', DEFAULT_OPTS);
        assert.equal(result.manifest.subagents, undefined);
    });
});

// ─── Workflow files ─────────────────────────────────────────────

describe('buildInitConfig workflow files', () => {
    it('includes workflow copy files with sourcePath', () => {
        const result = buildInitConfig('claudecode', DEFAULT_OPTS);
        const wfFiles = result.files.filter(f => f.path.startsWith(path.join('.omni', 'workflows')));
        assert.ok(wfFiles.length > 0, 'should have workflow files');
        for (const wf of wfFiles) {
            assert.ok(wf.sourcePath, `workflow ${wf.path} should have sourcePath`);
            assert.equal(wf.content, null, `workflow ${wf.path} should have null content (copy file)`);
            assert.equal(wf.overwritePrompt, false);
        }
    });
});

// ─── buildModeBlock (unit) ──────────────────────────────────────

describe('buildModeBlock', () => {
    it('common: brainstorm optional in both modes', () => {
        for (const m of ['auto', 'manual']) {
            const b = buildModeBlock(m);
            assert.ok(b.includes('## RUN MODE'));
            assert.ok(b.includes('Brainstorm KHÔNG bắt buộc'));
        }
    });

    it('auto contains equip→plan→cook auto-chain', () => {
        const b = buildModeBlock('auto');
        assert.ok(b.includes('Chế độ AUTO'));
        assert.ok(/skill.*→.*plan.*→.*cook/s.test(b));
    });

    it('manual contains MANUAL note and no auto-chain', () => {
        const b = buildModeBlock('manual');
        assert.ok(b.includes('Chế độ MANUAL'));
        assert.ok(!b.includes('Chế độ AUTO'));
    });

    it('defaults (unknown/empty) to manual', () => {
        assert.ok(buildModeBlock().includes('Chế độ MANUAL'));
    });
});

// ─── Run mode (auto/manual) ─────────────────────────────────────

describe('buildInitConfig run mode', () => {
    it('RUN MODE block + optional brainstorm always present', () => {
        const result = buildInitConfig('claudecode', { ...DEFAULT_OPTS, mode: 'manual' });
        const main = result.files.find(f => f.path === 'CLAUDE.md');
        assert.ok(main.content.includes('## RUN MODE'));
        assert.ok(main.content.includes('Brainstorm KHÔNG bắt buộc'));
        assert.equal(result.manifest.mode, 'manual');
        assert.equal(result.manifest.strictness, undefined);
    });

    it('auto mode embeds the equip→plan→cook auto-chain', () => {
        const result = buildInitConfig('claudecode', { ...DEFAULT_OPTS, mode: 'auto' });
        const main = result.files.find(f => f.path === 'CLAUDE.md');
        assert.ok(main.content.includes('Chế độ AUTO'));
        assert.ok(/skill.*→.*plan.*→.*cook/s.test(main.content));
        assert.equal(result.manifest.mode, 'auto');
    });

    it('manual mode states it does NOT auto-chain', () => {
        const result = buildInitConfig('claudecode', { ...DEFAULT_OPTS, mode: 'manual' });
        const main = result.files.find(f => f.path === 'CLAUDE.md');
        assert.ok(main.content.includes('Chế độ MANUAL'));
    });

    it('no strictness/hardcore/flexible leaks into config', () => {
        const result = buildInitConfig('claudecode', { ...DEFAULT_OPTS, mode: 'auto' });
        const main = result.files.find(f => f.path === 'CLAUDE.md');
        assert.ok(!/HARDCORE|FLEXIBLE|STRICTNESS LEVEL/.test(main.content));
    });
});
