'use strict';

function formatMarkdown(parsed) {
    const sections = [];
    if (parsed.language) sections.push(`## Ngôn ngữ\n- ${parsed.language}`);
    if (parsed.codingStyle.length > 0) sections.push(`## Coding Style\n${parsed.codingStyle.map(r => `- ${r}`).join('\n')}`);
    if (parsed.forbidden.length > 0) sections.push(`## Forbidden Patterns\n${parsed.forbidden.map(r => `- ${r}`).join('\n')}`);
    if (parsed.custom.length > 0) sections.push(`## Custom Rules\n${parsed.custom.map(r => `- ${r}`).join('\n')}`);
    if (sections.length === 0) return null;
    return `# Personal Rules\n> Generated by Omni-Coder Kit | Last updated: ${new Date().toISOString().split('T')[0]}\n\n${sections.join('\n\n')}\n`;
}

function formatInject(parsed) {
    const lines = [];
    if (parsed.language) lines.push(`- **Ngôn ngữ:** ${parsed.language}`);
    for (const r of parsed.codingStyle) lines.push(`- ${r}`);
    for (const r of parsed.forbidden) lines.push(`- **KHÔNG:** ${r}`);
    for (const r of parsed.custom) lines.push(`- ${r}`);
    return lines.join('\n');
}

module.exports = { formatMarkdown, formatInject };
