const fs = require('fs');
const path = require('path');

const PKG = require(path.join(__dirname, '..', 'package.json'));

const IDE_AGENT_MAP = {
    claudecode:  ['claude-code'],
    gemini:      ['gemini'],
    codex:       ['codex'],
    dual:        ['claude-code', 'codex'],
    antigravity: ['antigravity'],
    cursor:      ['cursor'],
    windsurf:    ['windsurf'],
    agents:      ['claude-code', 'codex', 'antigravity'],
    generic:     null,
};

const IDE_CONFIG_FILE = {
    claudecode: 'CLAUDE.md',
    gemini:     'GEMINI.md',
    codex:      'AGENTS.md',
    dual:       'CLAUDE.md',
    antigravity:'AGENTS.md',
    agents:     'AGENTS.md',
    cursor:     '.cursorrules',
    windsurf:   '.windsurfrules',
    generic:    'SYSTEM_PROMPT.md',
};

function parseSource(raw) {
    if (!raw) return null;
    let cleaned = raw.trim().replace(/\/+$/, '');
    const urlMatch = cleaned.match(/^https?:\/\/(?:www\.)?github\.com\/([a-zA-Z0-9_-]+\/[a-zA-Z0-9._-]+(?:\/.+)?)$/);
    if (urlMatch) cleaned = urlMatch[1];
    const sshMatch = cleaned.match(/^git@github\.com:([a-zA-Z0-9_-]+\/[a-zA-Z0-9._-]+?)(?:\.git)?$/);
    if (sshMatch) cleaned = sshMatch[1];
    cleaned = cleaned.replace(/\.git$/, '');
    if (cleaned.includes('..')) return null;
    if (!/^[a-zA-Z0-9_-]+\/[a-zA-Z0-9._-]+(\/.+)?$/.test(cleaned)) return null;
    return cleaned;
}

function isValidSkillName(name) {
    return /^[a-z0-9-]+$/.test(name);
}

function buildRulesContent(rp) {
    const sections = [];
    if (rp.language) sections.push(`## Ngôn ngữ\n- ${rp.language}`);
    if (rp.codingStyle) sections.push(`## Coding Style\n${rp.codingStyle.split(';').map(r => r.trim()).filter(Boolean).map(r => `- ${r}`).join('\n')}`);
    if (rp.forbidden) sections.push(`## Forbidden Patterns\n${rp.forbidden.split(';').map(r => r.trim()).filter(Boolean).map(r => `- ${r}`).join('\n')}`);
    if (rp.custom) sections.push(`## Custom Rules\n${rp.custom.split(';').map(r => r.trim()).filter(Boolean).map(r => `- ${r}`).join('\n')}`);
    if (sections.length === 0) return null;
    return `# Personal Rules\n> Generated by Omni-Coder Kit | Last updated: ${new Date().toISOString().split('T')[0]}\n\n${sections.join('\n\n')}\n`;
}

function extractRulesForInject(rp) {
    const lines = [];
    if (rp.language) lines.push(`- **Ngôn ngữ:** ${rp.language}`);
    if (rp.codingStyle) rp.codingStyle.split(';').map(r => r.trim()).filter(Boolean).forEach(r => lines.push(`- ${r}`));
    if (rp.forbidden) rp.forbidden.split(';').map(r => r.trim()).filter(Boolean).forEach(r => lines.push(`- **KHÔNG:** ${r}`));
    if (rp.custom) rp.custom.split(';').map(r => r.trim()).filter(Boolean).forEach(r => lines.push(`- ${r}`));
    return lines.join('\n');
}

function createManifest() {
    return { version: PKG.version, configFile: null, skills: { external: [] } };
}

function getAgentFlags(manifest) {
    const agents = IDE_AGENT_MAP[manifest.ide];
    if (!agents) return '';
    return `--agent ${agents.join(' ')}`;
}

function getOverlayNameForTarget(ide, target) {
    if (target === 'claude-code') {
        return (ide === 'claudecode' || ide === 'dual') ? 'claude-code' : null;
    }
    if (target === 'codex') {
        return (ide === 'codex' || ide === 'dual') ? 'codex' : null;
    }
    if (target === 'cursor') {
        return (ide === 'cursor') ? 'cursor' : null;
    }
    return null;
}

function detectDNA(projectDir) {
    let pkg = {};
    try {
        pkg = JSON.parse(fs.readFileSync(path.join(projectDir, 'package.json'), 'utf-8'));
    } catch {}
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    const hasDep = (name) => name in allDeps;
    const dirExists = (name) => fs.existsSync(path.join(projectDir, name));
    return {
        hasUI: hasDep('react') || hasDep('vue') || hasDep('svelte') || hasDep('next') || hasDep('@angular/core'),
        hasBackend: hasDep('express') || hasDep('fastify') || hasDep('hono') || hasDep('prisma') || hasDep('@supabase/supabase-js') || dirExists('server') || dirExists('api'),
        hasAPI: hasDep('express') || hasDep('fastify') || hasDep('hono') || dirExists('routes') || dirExists('controllers'),
    };
}

module.exports = {
    IDE_AGENT_MAP,
    IDE_CONFIG_FILE,
    parseSource,
    isValidSkillName,
    buildRulesContent,
    extractRulesForInject,
    createManifest,
    getAgentFlags,
    getOverlayNameForTarget,
    detectDNA,
};
