'use strict';

const fs = require('fs');
const path = require('path');
const { scanProject } = require('./scan');
const { formatLandminesForMap } = require('./landmines');

function generateMapSkeleton(scan, projectName) {
    const date = new Date().toISOString().split('T')[0];
    const lines = [];

    lines.push(`# Project Map — ${projectName}`);
    lines.push(`> Generated by omni map | ${date} | ${scan.stats.files} files, ${scan.stats.dirs} dirs, ~${scan.stats.loc} LOC`);
    lines.push(`> Last refresh: ${date} | Age: 0 days`);
    lines.push('');

    // Tech Stack
    lines.push('## Tech Stack');
    const ts = scan.techStack;
    const parts = [];
    if (ts.runtime) parts.push(`Runtime: ${ts.runtime}`);
    if (ts.language && ts.language !== ts.runtime) parts.push(`Lang: ${ts.language}`);
    if (ts.framework) parts.push(`Framework: ${ts.framework}`);
    if (ts.ui) parts.push(`UI: ${ts.ui}`);
    if (ts.db) parts.push(`DB: ${ts.db}`);
    if (ts.test) parts.push(`Test: ${ts.test}`);
    if (ts.queue) parts.push(`Queue: ${ts.queue}`);
    lines.push(parts.length > 0 ? parts.join(' | ') : '[No tech stack detected]');
    lines.push('');

    // Structure
    lines.push('## Structure');
    if (scan.structure.length > 0) {
        const dirs = scan.structure.filter(s => s.depth <= 2).sort((a, b) => a.path.localeCompare(b.path));
        for (const dir of dirs) {
            const indent = '  '.repeat(dir.depth);
            lines.push(`${indent}- \`${dir.path}\` (${dir.fileCount} files) [PENDING]`);
        }
    } else {
        lines.push('[No directories found]');
    }
    lines.push('');

    // Entry Points
    lines.push('## Entry Points');
    if (scan.entryPoints.length > 0) {
        for (const ep of scan.entryPoints) {
            lines.push(`- \`${ep.file}\` — ${ep.hint}`);
        }
    } else {
        lines.push('[No entry points detected]');
    }
    lines.push('');

    // CI/CD
    if (scan.ci.length > 0) {
        lines.push('## CI/CD');
        for (const c of scan.ci) {
            lines.push(`- \`${c.file}\` (${c.type})`);
        }
        lines.push('');
    }

    // Conventions
    lines.push('## Conventions');
    const conv = scan.conventions;
    if (conv.linter) lines.push(`- Linter: ${conv.linter}`);
    if (conv.formatter) lines.push(`- Formatter: ${conv.formatter}`);
    if (conv.tsconfig) lines.push('- TypeScript: strict (tsconfig.json)');
    if (conv.editorconfig) lines.push('- EditorConfig: yes');
    if (conv.commitConvention) lines.push(`- Commits: ${conv.commitConvention}`);
    if (!conv.linter && !conv.formatter && !conv.tsconfig) lines.push('[No conventions detected]');
    lines.push('');

    // Key Patterns
    lines.push('## Key Patterns');
    lines.push('[PENDING — AI fills this when running >om:map]');
    lines.push('');

    // Landmines
    lines.push('## Landmines');
    if (scan.landmines.length > 0) {
        lines.push(formatLandminesForMap(scan.landmines, 4));
    } else {
        lines.push('[No TODO/FIXME/HACK found]');
    }
    lines.push('');

    // Existing Docs
    lines.push('## Existing Docs');
    if (scan.docs.length > 0) {
        for (const d of scan.docs) {
            if (d.type === 'directory') {
                lines.push(`- \`${d.file}\` (${d.count} files)`);
            } else {
                lines.push(`- \`${d.file}\` (${d.lines} lines)`);
            }
        }
    } else {
        lines.push('[No docs found]');
    }
    lines.push('');

    return lines.join('\n');
}

function parseMapStructure(md) {
    const entries = {};
    const structureMatch = md.match(/## Structure\n([\s\S]*?)(?=\n## )/);
    if (!structureMatch) return entries;
    const lines = structureMatch[1].split('\n').filter(l => l.trim());
    for (const line of lines) {
        const match = line.match(/`([^`]+\/)`\s*(?:\((\d+) files?\))?\s*(.*)$/);
        if (match) {
            entries[match[1]] = { fileCount: match[2] ? parseInt(match[2]) : 0, description: match[3].trim() };
        }
    }
    return entries;
}

function refreshMap(dir) {
    const mapPath = path.join(dir, '.omni', 'knowledge', 'project-map.md');
    if (!fs.existsSync(mapPath)) return null;

    const existingMd = fs.readFileSync(mapPath, 'utf-8');
    const oldEntries = parseMapStructure(existingMd);
    const newScan = scanProject(dir);
    const today = new Date().toISOString().split('T')[0];

    const newDirs = new Set(newScan.structure.filter(s => s.depth <= 2).map(s => s.path));
    const oldDirs = new Set(Object.keys(oldEntries));

    let md = existingMd;

    // Update header
    md = md.replace(/Last refresh: \S+/, `Last refresh: ${today}`);
    md = md.replace(/Age: \d+ days/, 'Age: 0 days');
    const statsMatch = md.match(/\| \d+ files, \d+ dirs, ~\d+ LOC/);
    if (statsMatch) {
        md = md.replace(statsMatch[0], `| ${newScan.stats.files} files, ${newScan.stats.dirs} dirs, ~${newScan.stats.loc} LOC`);
    }

    // Rebuild structure section preserving descriptions
    const structureLines = [];
    const allDirs = new Set([...newDirs, ...oldDirs]);
    const sorted = [...allDirs].sort();
    for (const dirPath of sorted) {
        const scanEntry = newScan.structure.find(s => s.path === dirPath);
        const oldEntry = oldEntries[dirPath];
        const depth = (dirPath.match(/\//g) || []).length - 1;
        const indent = '  '.repeat(Math.max(0, depth));

        if (scanEntry && !oldEntry) {
            structureLines.push(`${indent}- \`${dirPath}\` (${scanEntry.fileCount} files) [NEW]`);
        } else if (!scanEntry && oldEntry) {
            structureLines.push(`${indent}- \`${dirPath}\` [DELETED]`);
        } else if (scanEntry && oldEntry) {
            const desc = oldEntry.description || '[PENDING]';
            structureLines.push(`${indent}- \`${dirPath}\` (${scanEntry.fileCount} files) ${desc}`);
        }
    }

    md = md.replace(/## Structure\n[\s\S]*?(?=\n## )/, `## Structure\n${structureLines.join('\n')}\n`);

    // Update tech stack (overwrite)
    const ts = newScan.techStack;
    const parts = [];
    if (ts.runtime) parts.push(`Runtime: ${ts.runtime}`);
    if (ts.language && ts.language !== ts.runtime) parts.push(`Lang: ${ts.language}`);
    if (ts.framework) parts.push(`Framework: ${ts.framework}`);
    if (ts.ui) parts.push(`UI: ${ts.ui}`);
    if (ts.db) parts.push(`DB: ${ts.db}`);
    if (ts.test) parts.push(`Test: ${ts.test}`);
    if (ts.queue) parts.push(`Queue: ${ts.queue}`);
    const newStack = parts.length > 0 ? parts.join(' | ') : '[No tech stack detected]';
    md = md.replace(/## Tech Stack\n.*?\n/, `## Tech Stack\n${newStack}\n`);

    return md;
}

module.exports = { generateMapSkeleton, parseMapStructure, refreshMap };
