'use strict';

const fs = require('fs');
const path = require('path');
const prompts = require('prompts');
const chalk = require('chalk');
const { execFileSync } = require('child_process');

const { parseSource, isValidSkillName, getAgentFlags } = require('../helpers');
const { detectExistingProject, scanProject } = require('../scanner');
const { UNIVERSAL_SKILLS, getTestSkillsForStack, buildSearchSuggestion } = require('../skills');
const {
    MANIFEST_FILE, findConfigFile, writeFileSafe, loadManifest, saveManifest, findSkillConflict,
} = require('./helpers');

async function handleEquip(source, options) {
    const parsedSource = parseSource(source);
    if (!parsedSource) {
        console.log(chalk.red.bold(`\n❌ Source không hợp lệ. Định dạng đúng: owner/repo hoặc URL GitHub.\n`));
        return;
    }

    const skillName = options.name || parsedSource.split('/').pop().toLowerCase().replace(/[^a-z0-9-]/g, '-');

    if (!isValidSkillName(skillName)) {
        console.log(chalk.red.bold(`\n❌ Tên kỹ năng "${skillName}" không hợp lệ. Dùng --name <tên> để đặt tên thủ công.\n`));
        return;
    }

    const configFile = findConfigFile();
    if (!configFile) {
        console.log(chalk.red.bold('\n❌ Không tìm thấy file Omni. Hãy chạy "omni init" trước.\n'));
        return;
    }

    const manifest = loadManifest();

    const conflict = findSkillConflict(manifest, skillName);
    if (conflict && !options.force) {
        const via = 'omni equip';
        console.log(chalk.yellow.bold(`\n⚠️  Kỹ năng "${skillName}" đã được cài đặt trước đó (qua ${via}).`));
        console.log(chalk.yellow(`   Dùng thêm cờ ${chalk.cyan('--force')} nếu bạn muốn ghi đè.\n`));
        return;
    }

    const agentFlags = getAgentFlags(manifest);
    console.log(chalk.cyan.bold(`\n🔧 Đang cài đặt kỹ năng external: ${chalk.white(parsedSource)}`));
    if (agentFlags) console.log(chalk.gray(`   Target: ${agentFlags}`));
    console.log('');

    try {
        const args = ['skills', 'add', parsedSource];
        if (agentFlags) args.push(...agentFlags.split(' '));
        execFileSync('npx', args, { stdio: 'inherit' });
    } catch (err) {
        console.log(chalk.red.bold(`\n❌ Quá trình cài đặt thất bại. Vui lòng kiểm tra lại source hoặc mạng.\n`));
        return;
    }

    if (!conflict) {
        manifest.skills.external.push({
            name: skillName,
            source: parsedSource,
            installedAt: new Date().toISOString()
        });
    } else if (conflict.type === 'external') {
        const ext = manifest.skills.external.find(s => s.name === skillName);
        if (ext) {
            ext.source = parsedSource;
            ext.installedAt = new Date().toISOString();
        }
    }

    manifest.configFile = configFile;
    saveManifest(manifest);

    console.log(chalk.green.bold(`\n✅ Kỹ năng [${skillName}] đã được cài đặt và đồng bộ thành công!`));
    console.log(chalk.gray(`   Source: ${parsedSource}`));
    console.log(chalk.gray(`   Manifest: ${MANIFEST_FILE}\n`));
}

function generateRetryScript(failedSkills, agentFlags) {
    let script = '#!/bin/bash\n';
    script += '# Generated by Omni-Coder Kit — retry failed skills\n';
    script += `# Failed: ${failedSkills.length} skills\n\n`;
    script += 'set -e\n\n';

    for (const skill of failedSkills) {
        const installCmd = agentFlags
            ? `npx -y skills add ${skill.source} ${agentFlags} --skill '*' -y`
            : `npx -y skills add ${skill.source} --all`;
        script += `echo "🔧 Đang cài: ${skill.name} (${skill.source})..."\n`;
        script += `${installCmd}\n`;
        script += `echo "   ✓ ${skill.name}"\n\n`;
    }

    script += `echo ""\necho "✅ Hoàn tất! Đã cài ${failedSkills.length} skills."\n`;
    script += `echo "💡 Chạy 'omni status' để xem trạng thái."\n`;
    return script;
}

async function handleAutoEquip(options) {
    const configFile = findConfigFile();
    if (!configFile) {
        console.log(chalk.red.bold('\n❌ Không tìm thấy file Omni. Hãy chạy "omni init" trước.\n'));
        return;
    }

    const manifest = loadManifest();
    const alreadyInstalled = manifest.skills.external.map(s => s.name);
    const toInstall = UNIVERSAL_SKILLS.filter(s => !alreadyInstalled.includes(s.name));

    if (toInstall.length === 0) {
        console.log(chalk.green.bold('\n✅ Tất cả skills đã được cài đặt rồi! Dùng "omni status" để xem chi tiết.\n'));
        return;
    }

    console.log(chalk.cyan.bold('📦 Danh sách skills sẽ được cài từ skills.sh:\n'));
    toInstall.forEach((s, i) => {
        const badge = alreadyInstalled.includes(s.name) ? chalk.gray('(đã có)') : chalk.green('MỚI');
        console.log(chalk.white(`   ${i + 1}. ${chalk.bold(s.name)} ${badge}`));
        console.log(chalk.gray(`      └─ ${s.desc} (${s.source})`));
    });
    console.log('');

    const agentFlags = getAgentFlags(manifest);

    if (!options.yes) {
        const { confirmed } = await prompts({
            type: 'confirm',
            name: 'confirmed',
            message: `Cài đặt ${toInstall.length} skills trên? (y/N)`,
            initial: false
        });

        if (!confirmed) {
            console.log(chalk.yellow('\n⚠️  Hủy bỏ.\n'));
            return;
        }
    } else {
        console.log(chalk.green(`⚡ Auto-install: ${toInstall.length} skills (project-level)\n`));
    }

    let installed = 0;
    let failed = 0;

    if (agentFlags) {
        console.log(chalk.gray(`   Target: ${agentFlags}\n`));
    }

    for (const skill of toInstall) {
        console.log(chalk.cyan(`\n🔧 [${installed + failed + 1}/${toInstall.length}] Đang cài: ${chalk.white(skill.name)}...`));
        try {
            const skillArgs = ['-y', 'skills', 'add', skill.source];
            if (agentFlags) {
                skillArgs.push(...agentFlags.split(' '), '--skill', '*', '-y');
            } else if (options.yes) {
                skillArgs.push('--all');
            }
            execFileSync('npx', skillArgs, { stdio: 'inherit', timeout: 60000 });
            manifest.skills.external.push({
                name: skill.name,
                source: skill.source,
                installedAt: new Date().toISOString()
            });
            installed++;
            console.log(chalk.green(`   ✓ ${skill.name}`));
        } catch {
            failed++;
            console.log(chalk.red(`   ✗ ${skill.name} — thất bại, bỏ qua`));
        }
    }

    manifest.configFile = configFile;
    saveManifest(manifest);

    console.log(chalk.cyan.bold('\n' + '─'.repeat(45)));
    console.log(chalk.green.bold(`   ✅ Thành công: ${installed}/${toInstall.length} skills`));
    if (failed > 0) {
        console.log(chalk.red(`   ❌ Thất bại: ${failed} skills`));

        const failedSkills = toInstall.filter(s => !manifest.skills.external.some(e => e.name === s.name));
        if (failedSkills.length > 0) {
            const scriptName = 'install-skills.sh';
            const scriptPath = path.join(process.cwd(), scriptName);
            const script = generateRetryScript(failedSkills, agentFlags);

            if (writeFileSafe(scriptPath, script)) {
                try { fs.chmodSync(scriptPath, '755'); } catch {}
                console.log(chalk.yellow(`\n   💡 Đã tạo ${chalk.white(scriptName)} cho ${failedSkills.length} skill thất bại.`));
                console.log(chalk.yellow(`      Có thể do sandbox chặn mạng (Codex CLI, etc.).`));
                console.log(chalk.white(`      Chạy ngoài sandbox: `) + chalk.cyan.bold(`bash ${scriptName}`));
            }
        }
    }
    console.log(chalk.gray(`   Manifest: ${MANIFEST_FILE}`));
    console.log(chalk.cyan.bold('─'.repeat(45) + '\n'));

    // Phase 2: Detect tech stack → propose test skills
    const detected = detectExistingProject(process.cwd());
    if (!detected.detected) {
        console.log(chalk.gray('   ⚠️ Không phát hiện project — bỏ qua đề xuất test skills.\n'));
        return;
    }

    const scan = scanProject(process.cwd());
    if (!scan.techStack || !scan.techStack.language) {
        console.log(chalk.gray('   ℹ️ Không xác định được ngôn ngữ chính — bỏ qua test skills.\n'));
        return;
    }

    const testSkills = getTestSkillsForStack(scan.techStack);

    if (testSkills.length === 0) {
        const keyword = buildSearchSuggestion(scan.techStack.language, scan.techStack.test);
        console.log(chalk.yellow(`\n   🔍 Chưa có curated test skill cho ${chalk.white(scan.techStack.language)}.`));
        console.log(chalk.gray(`      Gợi ý: dùng lệnh ${chalk.cyan('>om:equip')} hoặc tìm thủ công:`));
        console.log(chalk.cyan(`      npx skills search "${keyword}"\n`));
        return;
    }

    const installedNames = manifest.skills.external.map(s => s.name);
    const testToInstall = testSkills.filter(s => !installedNames.includes(s.name));

    if (testToInstall.length === 0) return;

    console.log(chalk.cyan.bold('🧪 Phát hiện tech stack — đề xuất test skills:\n'));
    const stackLabel = [scan.techStack.language, scan.techStack.test].filter(Boolean).join(' + ');
    console.log(chalk.gray(`   Stack: ${stackLabel}\n`));
    testToInstall.forEach((s, i) => {
        console.log(chalk.white(`   ${i + 1}. ${chalk.bold(s.name)} ${chalk.green('MỚI')}`));
        console.log(chalk.gray(`      └─ ${s.desc} (${s.source})`));
    });
    console.log('');

    if (!options.yes) {
        const { installTest } = await prompts({
            type: 'confirm',
            name: 'installTest',
            message: `Cài thêm ${testToInstall.length} test skill${testToInstall.length > 1 ? 's' : ''}? (y/N)`,
            initial: false
        });
        if (!installTest) return;
    } else {
        console.log(chalk.green(`⚡ Auto-install: ${testToInstall.length} test skill(s)\n`));
    }

    let testInstalled = 0;
    for (const skill of testToInstall) {
        console.log(chalk.cyan(`\n🧪 Đang cài: ${chalk.white(skill.name)}...`));
        try {
            const skillArgs = ['-y', 'skills', 'add', skill.source];
            if (agentFlags) {
                skillArgs.push(...agentFlags.split(' '), '--skill', skill.name, '-y');
            } else {
                skillArgs.push('--skill', skill.name, '-y');
            }
            execFileSync('npx', skillArgs, { stdio: 'inherit', timeout: 60000 });
            manifest.skills.external.push({
                name: skill.name,
                source: skill.source,
                installedAt: new Date().toISOString(),
                category: 'testing'
            });
            testInstalled++;
            console.log(chalk.green(`   ✓ ${skill.name}`));
        } catch {
            console.log(chalk.red(`   ✗ ${skill.name} — thất bại, bỏ qua`));
        }
    }

    if (testInstalled > 0) {
        saveManifest(manifest);
        console.log(chalk.green.bold(`\n   🧪 Test skills: ${testInstalled}/${testToInstall.length} cài thành công\n`));
    }
}

module.exports = { handleEquip, handleAutoEquip };
